import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico, Quicksand, Tektur } from "next/font/google";
import "./globals.css";
import React from "react";
import FlashMessage from "./FlashMessage";
import Footer from "./Footer";
import PageTransitionSpinner from "./PageTransitionSpinner";
import { CartProvider } from "./CartContext";
import CartIconWithModal from "./CartIconWithModal";
import OrderNotification from "./OrderNotification";
import ChatSupport from "./ChatSupport";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
  display: "swap",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  display: "swap",
});

const tektur = Tektur({
  subsets: ["latin"],
  variable: "--font-tektur",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${quicksand.variable} ${tektur.variable}`}
      >
        <CartProvider>
          <PageTransitionSpinner />
          <OrderNotification />
          <CartIconWithModal />
          <ChatSupport />
        {children}
        <FlashMessage />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
